"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { faqs, policyContent, posts, product, products, reviews } from "./data";
import { createShopifyCheckout, getShopifyProducts, shopifyConfigured } from "./shopify";

type CartLine = { variant: string; qty: number; productSlug?: string; shopifyId?: string; title?: string; variantTitle?: string; price?: number; image?: string };
const icons = { search: "⌕", cart: "◒", menu: "☰", close: "×", arrow: "→", check: "✓" };
const money = (n:number, currency="USD") => {
  let amount = n;
  if (product.currency === "VND" && currency === "USD") amount = n / 26000;
  if (product.currency === "USD" && currency === "VND") amount = n * 26000;
  const shownCurrency = ["USD", "VND"].includes(product.currency) ? currency : product.currency;
  return new Intl.NumberFormat("en-US", { style:"currency", currency:shownCurrency, maximumFractionDigits:shownCurrency === "VND" ? 0 : 2 }).format(amount);
};
const shippingTarget = () => product.currency === "VND" ? 600000 : 25;

function useCart() {
  const [lines, setLines] = useState<CartLine[]>([]); const [ready,setReady]=useState(false);
  useEffect(()=>{ try { setLines(JSON.parse(localStorage.getItem("furlo-cart")||"[]")); } catch {} setReady(true); },[]);
  useEffect(()=>{ if(ready) localStorage.setItem("furlo-cart",JSON.stringify(lines)); },[lines,ready]);
  const add=(variant="single",qty=1)=>setLines(ls=>{const selected=product.variants.find(item=>item.id===variant)||product.variants[0];const hit=ls.find(x=>x.variant===selected.id&&x.productSlug===product.slug);return hit?ls.map(x=>x===hit?{...x,qty:x.qty+qty}:x):[...ls,{variant:selected.id,qty,productSlug:product.slug,shopifyId:selected.shopifyId,title:product.title,variantTitle:selected.title,price:selected.price,image:product.images[0]}]});
  const update=(variant:string,qty:number)=>setLines(ls=>qty<1?ls.filter(x=>x.variant!==variant):ls.map(x=>x.variant===variant?{...x,qty}:x));
  const total=lines.reduce((s,l)=>s+(l.price||product.variants.find(v=>v.id===l.variant)?.price||product.price)*l.qty,0);
  const checkout=async(discountCode?:string,note?:string)=>{
    if(!shopifyConfigured){alert("Shopify is ready to connect. Add your store domain and Storefront token to enable live checkout.");return;}
    const checkoutLines=lines.map(line=>({merchandiseId:line.shopifyId||product.variants.find(variant=>variant.id===line.variant)?.shopifyId||"",quantity:line.qty})).filter(line=>line.merchandiseId);
    if(!checkoutLines.length){alert("This cart does not contain a Shopify product variant yet.");return;}
    const checkoutUrl=await createShopifyCheckout(checkoutLines,discountCode,note);window.location.href=checkoutUrl;
  };
  return {lines,add,update,checkout,total,count:lines.reduce((s,l)=>s+l.qty,0)};
}

export function Storefront({route,slug}:{route:string;slug?:string}) {
  const cart=useCart(); const [drawer,setDrawer]=useState<"cart"|"menu"|"search"|null>(null); const [currency,setCurrency]=useState("USD");
  const [,setCatalogRevision]=useState(0);
  useEffect(()=>{if(!shopifyConfigured)return;getShopifyProducts().then(live=>{if(!live.length)return;products.splice(0,products.length,...live);Object.assign(product,live.find(item=>item.slug===slug)||live[0]);setCurrency(product.currency);setCatalogRevision(value=>value+1)}).catch(error=>console.warn("Shopify catalog fallback:",error.message))},[slug]);
  useEffect(()=>{const c=localStorage.getItem("furlo-currency-en");if(c)setCurrency(c)},[]);
  useEffect(()=>{localStorage.setItem("furlo-currency-en",currency);document.body.style.overflow=drawer?"hidden":"";return()=>{document.body.style.overflow=""}},[drawer,currency]);
  useEffect(()=>{const esc=(e:KeyboardEvent)=>e.key==="Escape"&&setDrawer(null);window.addEventListener("keydown",esc);return()=>window.removeEventListener("keydown",esc)},[]);
  const add=(variant="single",qty=1)=>{cart.add(variant,qty);setDrawer("cart")};
  const page = route === "home" ? <Home add={add} currency={currency}/> : route === "shop" ? <Shop add={add} currency={currency}/> : route === "product" ? <Product add={add} currency={currency}/> : route === "cart" ? <CartPage cart={cart} currency={currency}/> : route === "search" ? <SearchPage add={add} currency={currency}/> : route === "faq" ? <FAQ/> : route === "contact" ? <Contact/> : route === "track" ? <Track/> : route === "blog" ? <Blog slug={slug}/> : route === "404" ? <NotFound/> : <Policy kind={route}/>;
  return <><Announcement/><Header count={cart.count} open={setDrawer} currency={currency} setCurrency={setCurrency}/><main>{page}</main><Footer currency={currency} setCurrency={setCurrency}/>{drawer&&<Overlay kind={drawer} close={()=>setDrawer(null)} cart={cart} currency={currency} add={add}/>}<Cookie/></>;
}

function Announcement(){return <div className="announcement"><span>Free shipping on orders over $25</span><span className="announce-extra">30-day returns · Support seven days a week</span></div>}
function Header({count,open,currency,setCurrency}:{count:number;open:(x:"cart"|"menu"|"search")=>void;currency:string;setCurrency:(s:string)=>void}){return <header className="header"><div className="nav shell"><button className="icon mobile" onClick={()=>open("menu")} aria-label="Open menu">{icons.menu}</button><a className="logo" href="/">FUR<span>LO</span><small>BETTER DAYS WITH PETS</small></a><nav><a href="/shop">Shop</a><a href="/about">Our Story</a><a href="/blog">Journal</a><a href="/faq">FAQ</a></nav><div className="nav-actions"><select value={currency} onChange={e=>setCurrency(e.target.value)} aria-label="Currency"><option>USD</option><option>VND</option></select><button className="icon" onClick={()=>open("search")} aria-label="Search">{icons.search}</button><button className="icon cart-button" onClick={()=>open("cart")} aria-label={`Cart with ${count} items`}>{icons.cart}<b>{count}</b></button></div></div></header>}

function Home({add,currency}:{add:(v?:string,q?:number)=>void;currency:string}){return <>
  <section className="hero"><img src={product.images[0]} alt="FURLO pet hair removal mitt"/><div className="hero-copy"><p className="eyebrow">GENTLE ON FABRIC. POWERFUL ON FUR.</p><h1>Less fur.<br/><em>More life together.</em></h1><p>One effortless sweep lifts embedded fur from sofas, bedding, and clothes. No sticky residue. No replacement rolls.</p><button className="button light" onClick={()=>add()}>Shop now · {money(product.price,currency)}</button></div><a href="#story" className="scroll">DISCOVER ↓</a></section>
  <section className="ticker"><div>THOUGHTFULLY DESIGNED ✦ TESTED IN REAL HOMES ✦ EFFORTLESS EVERY DAY ✦</div></section>
  <section id="story" className="intro shell reveal"><p className="eyebrow">A GENUINELY SMARTER SOLUTION</p><h2>We start with the little frictions<br/>of everyday life with pets.</h2><p>Then we keep designing until cleanup feels as natural as a sweep of your hand.</p></section>
  <section className="values shell"><Value n="01" title="Clean in one sweep" text="Two surfaces work together to lift and capture fur."/><Value n="02" title="Gentle at home" text="No sticky residue and no chemicals left on fabric."/><Value n="03" title="Made to be reused" text="Rinse, air-dry, and reach for it again and again."/></section>
  <section className="featured shell"><div className="product-visual"><span className="badge">BESTSELLER</span><img src={product.images[4]} alt="The two sides of the FURLO mitt"/></div><div className="product-copy"><p className="eyebrow">FEATURED PRODUCT</p><h2>{product.title}</h2><div className="stars">★★★★★ <span>4.9 · 326 reviews</span></div><p className="lede">{product.shortDescription}</p><ul>{product.benefits.map(x=><li key={x}>{icons.check} {x}</li>)}</ul><div className="price"><strong>{money(product.price,currency)}</strong><s>{money(product.compareAtPrice,currency)}</s><span>-37%</span></div><button className="button" onClick={()=>add()}>Add to cart {icons.arrow}</button><a className="text-link" href={`/products/${product.slug}`}>View product details</a></div></section>
  <section className="split-story"><div className="split-image"><img src={product.images[3]} alt="Cleaning a sofa with FURLO"/></div><div className="split-copy"><p className="eyebrow">FROM FURRY TO FRESH</p><h2>Not just surface clean.<br/><em>Fur lifted from the fabric.</em></h2><p>Directional microfiber grips embedded hair. The static-lift surface attracts loose fur. Two mechanisms, one simple movement.</p><a className="button outline" href={`/products/${product.slug}`}>See why it works</a></div></section>
  <section className="how shell"><p className="eyebrow">EFFORTLESS FROM THE FIRST USE</p><h2>Three steps. One clean surface.</h2><div className="steps"><Step n="1" title="Slip it on" text="The breathable mesh strap keeps the mitt secure."/><Step n="2" title="Sweep one way" text="Move slowly across the surface to gather fur."/><Step n="3" title="Lift & reuse" text="Remove the fur, rinse when needed, and air-dry."/></div></section>
  <section className="process"><div className="shell"><p className="eyebrow">INSIDE FURLO</p><h2>Observe. Test.<br/>Refine. Simplify.</h2><div className="process-grid">{["Spot the everyday friction","Try it in real homes","Tune every detail","Keep only what matters"].map((x,i)=><div key={x}><b>0{i+1}</b><h3>{x}</h3></div>)}</div></div></section>
  <ReviewSection/>
  <section className="promise shell"><div><b>30</b><span>day returns</span></div><div><b>0</b><span>replacement rolls</span></div><div><b>2</b><span>cleaning surfaces</span></div><div><b>1</b><span>minute to begin</span></div></section>
  <FAQ/>
  <Newsletter/>
  </>}
function Value({n,title,text}:{n:string;title:string;text:string}){return <article className="value"><span>{n}</span><h3>{title}</h3><p>{text}</p></article>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <article><b>{n}</b><h3>{title}</h3><p>{text}</p></article>}

function Shop({add,currency}:{add:(v?:string)=>void;currency:string}){return <section className="page shell"><div className="page-head"><p className="eyebrow">SMALL TOOLS. MEANINGFUL DIFFERENCE.</p><h1>Shop</h1><p>Thoughtful products shaped by real needs in homes with pets.</p></div><div className="collection">{products.map((item,index)=><article className="card" key={item.id}><a href={`/products/${item.slug}`}><img src={item.images[0]} alt={item.title}/>{index===0&&<span className="badge">BESTSELLER</span>}</a><h2>{item.title}</h2><p>{item.subtitle}</p><div><strong>{item.currency===product.currency?money(item.price,currency):new Intl.NumberFormat("en-US",{style:"currency",currency:item.currency}).format(item.price)}</strong> {item.compareAtPrice>item.price&&<s>{item.currency===product.currency?money(item.compareAtPrice,currency):new Intl.NumberFormat("en-US",{style:"currency",currency:item.currency}).format(item.compareAtPrice)}</s>}</div>{index===0?<button className="button" onClick={()=>add()}>Quick add</button>:<a className="button" href={`/products/${item.slug}`}>View product</a>}</article>)}</div></section>}

function Product({add,currency}:{add:(v?:string,q?:number)=>void;currency:string}){const [image,setImage]=useState(0),[variant,setVariant]=useState("single"),[qty,setQty]=useState(1);const current=product.variants.find(v=>v.id===variant)||product.variants[0];useEffect(()=>{setVariant(product.variants[0]?.id||"single");setImage(0)},[product.id]);useEffect(()=>history.replaceState(null,"",`/products/${product.slug}?variant=${variant}`),[variant]);return <><section className="product-page shell"><div className="gallery"><div className="main-image"><img src={product.images[image]} alt={`${product.title}, image ${image+1}`}/><button className="zoom" onClick={()=>window.open(product.images[image],"_blank")} aria-label="Zoom image">＋</button></div><div className="thumbs">{product.images.map((x,i)=><button className={i===image?"active":""} onClick={()=>setImage(i)} key={x}><img src={x} alt=""/></button>)}</div></div><div className="pdp-info"><p className="crumb"><a href="/">Home</a> / Shop / {product.title}</p><span className="pill">A PET-PARENT FAVORITE</span><h1>{product.title}</h1><p className="subtitle">{product.subtitle}</p><div className="stars">★★★★★ <a href="#reviews">4.9 (326)</a></div><div className="price large"><strong>{money(current.price,currency)}</strong>{product.compareAtPrice>current.price&&<s>{money(product.compareAtPrice,currency)}</s>}</div><p className="lede">{product.shortDescription}</p><fieldset><legend>Choose your option</legend><div className="variants">{product.variants.map(v=><button className={variant===v.id?"active":""} key={v.id} onClick={()=>setVariant(v.id)} disabled={v.available===false}><b>{v.title}</b><span>{money(v.price,currency)}</span></button>)}</div></fieldset><p className="stock"><i/> {current.available===false?"Out of stock":"In stock — ready to ship"}</p><div className="buy-row"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><span>{qty}</span><button onClick={()=>setQty(qty+1)}>＋</button></div><button className="button" disabled={current.available===false} onClick={()=>add(variant,qty)}>Add to cart · {money(current.price*qty,currency)}</button></div><button className="button buy-now" disabled={current.available===false} onClick={()=>{add(variant,qty);location.href="/cart"}}>Buy now</button><div className="micro"><span>🚚 Delivery calculated by Shopify</span><span>↺ 30-day returns</span><span>🔒 Secure Shopify checkout</span></div><Details/></div></section><section className="product-band"><img src={product.images[Math.min(2,product.images.length-1)]} alt="Product details"/><div><p className="eyebrow">THOUGHTFULLY DESIGNED</p><h2>Practical details.<br/>Effortless every day.</h2><p>Product information, pricing, and availability stay in sync with Shopify.</p></div></section><ReviewSection/><FAQ productOnly/></>}
function Details(){return <div className="details"><details open><summary>Description</summary><p>{product.description}</p></details><details><summary>Specifications</summary><ul>{product.specifications.map(x=><li key={x}>{x}</li>)}</ul></details><details><summary>How to use</summary><ol>{product.instructions.map(x=><li key={x}>{x}</li>)}</ol></details><details><summary>Shipping & returns</summary><p>Worldwide delivery is available. Returns are accepted within 30 days.</p></details></div>}

function ReviewSection(){return <section id="reviews" className="reviews"><div className="shell"><p className="eyebrow">STORIES FROM REAL HOMES</p><div className="review-title"><h2>What pet parents say</h2><div><b>4.9</b><span>★★★★★<br/>326 reviews</span></div></div><div className="review-grid">{reviews.map(r=><article key={r.name}><div className="stars">{"★".repeat(r.stars)}{"☆".repeat(5-r.stars)}</div><blockquote>“{r.text}”</blockquote><b>{r.name}</b><span>{r.pet} · Verified buyer</span></article>)}</div></div></section>}
function FAQ({productOnly=false}:{productOnly?:boolean}){return <section className="faq shell"><div><p className="eyebrow">{productOnly?"KNOW BEFORE YOU SWEEP":"GOT QUESTIONS?"}</p><h2>{productOnly?"About the FURLO mitt":"We have answers."}</h2><p>Need more help? <a href="/contact">Talk to FURLO</a>.</p></div><div className="faq-list">{faqs.map((f,i)=><details key={f[0]} open={i===0}><summary>{f[0]}<span>＋</span></summary><p>{f[1]}</p></details>)}</div></section>}

function CartPage({cart,currency}:{cart:ReturnType<typeof useCart>;currency:string}){return <section className="page shell"><div className="page-head"><h1>Your cart</h1></div>{cart.lines.length?<div className="cart-page"><CartLines cart={cart} currency={currency}/><CartSummary cart={cart} currency={currency}/></div>:<EmptyCart/>}</section>}
function CartLines({cart,currency}:{cart:ReturnType<typeof useCart>;currency:string}){return <div className="cart-lines">{cart.lines.map(l=>{const v=product.variants.find(x=>x.id===l.variant);return <article key={`${l.productSlug||"demo"}-${l.variant}`}><img src={l.image||product.images[0]} alt=""/><div><h3>{l.title||product.title}</h3><span>{l.variantTitle||v?.title}</span><strong>{money(l.price||v?.price||product.price,currency)}</strong><div className="qty small"><button onClick={()=>cart.update(l.variant,l.qty-1)}>−</button><span>{l.qty}</span><button onClick={()=>cart.update(l.variant,l.qty+1)}>＋</button></div><button className="remove" onClick={()=>cart.update(l.variant,0)}>Remove</button></div></article>})}</div>}
function CartSummary({cart,currency}:{cart:ReturnType<typeof useCart>;currency:string}){const left=Math.max(0,shippingTarget()-cart.total),[code,setCode]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const go=async()=>{setBusy(true);setError("");try{await cart.checkout(code,note)}catch(e){setError(e instanceof Error?e.message:"Checkout could not be started.")}finally{setBusy(false)}};return <aside className="summary"><h2>Order summary</h2><div className="progress"><span style={{width:`${Math.min(100,cart.total/shippingTarget()*100)}%`}}/></div><p>{left?`Add ${money(left,currency)} more for free shipping.`:"You have unlocked free shipping!"}</p><label>Discount code<input placeholder="FURLO10" value={code} onChange={event=>setCode(event.target.value)}/></label><label>Order note<textarea placeholder="Add a note to your order..." value={note} onChange={event=>setNote(event.target.value)}/></label><div className="subtotal"><span>Subtotal</span><strong>{money(cart.total,currency)}</strong></div>{error&&<p role="alert" className="checkout-error">{error}</p>}<button className="button" disabled={busy} onClick={go}>{busy?"Opening secure checkout…":"Continue to Shopify checkout"}</button><small>Taxes and shipping are calculated securely by Shopify.</small></aside>}
function EmptyCart(){return <div className="empty"><div>◌</div><h2>Your cart is waiting for something useful.</h2><p>Discover thoughtful tools made for easier days with pets.</p><a className="button" href="/shop">Explore the shop</a></div>}

function SearchPage({add,currency}:{add:(v?:string)=>void;currency:string}){const [q,setQ]=useState("");const found=!q||product.title.toLowerCase().includes(q.toLowerCase())||"fur sofa mitt".includes(q.toLowerCase());return <section className="page shell search-page"><div className="page-head"><p className="eyebrow">FIND WHAT YOU NEED</p><h1>Search</h1></div><label className="big-search">{icons.search}<input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products and stories..."/></label>{found?<div className="search-result"><img src={product.images[0]} alt=""/><div><p>PRODUCT</p><h2>{product.title}</h2><strong>{money(product.price,currency)}</strong></div><button className="button" onClick={()=>add()}>Add to cart</button></div>:<div className="empty"><h2>No results for “{q}”</h2><p>Try a shorter phrase such as “mitt”, “fur”, or “sofa”.</p></div>}</section>}

function Contact(){const [sent,setSent]=useState(false);return <section className="page shell contact"><div className="page-head"><p className="eyebrow">WE ARE LISTENING</p><h1>Contact FURLO</h1><p>Ask about a product, an order, or simply tell us about your four-legged friend.</p></div>{sent?<div className="success"><b>{icons.check}</b><h2>Your message is with FURLO.</h2><p>We will reply within one business day.</p></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Full name<input required/></label><label>Email<input required type="email"/></label><label>Topic<select><option>Product</option><option>Order</option><option>Returns</option></select></label><label>Message<textarea required rows={5}/></label><button className="button">Send message</button></form>}</section>}
function Track(){const [code,setCode]=useState(""),[result,setResult]=useState(false);return <section className="page track"><div><p className="eyebrow">YOUR ORDER'S JOURNEY</p><h1>Track your order</h1><p>Enter your order number and email to see the latest update.</p><form onSubmit={e=>{e.preventDefault();setResult(true)}}><label>Order number<input required placeholder="E.G. FR10284" value={code} onChange={e=>setCode(e.target.value)}/></label><label>Order email<input required type="email" placeholder="you@email.com"/></label><button className="button">Check status</button></form>{result&&<div className="tracking"><span>Order {code || "FR10284"}</span><h3>On the way to you</h3><div><i className="done"/><i className="done"/><i className="active"/><i/></div><p>Confirmed <b>Packed</b> In transit <span>Delivered</span></p></div>}</div><img src={product.images[1]} alt="FURLO in a fresh home"/></section>}

function Policy({kind}:{kind:string}){const p=policyContent[kind]||policyContent.about;return <section className="page policy shell"><div className="page-head"><p className="eyebrow">FURLO / INFORMATION</p><h1>{p.title}</h1><p>{p.intro}</p></div><div className="policy-body">{p.sections.map(([h,t],i)=><section key={h}><span>0{i+1}</span><div><h2>{h}</h2><p>{t}</p></div></section>)}</div></section>}
function Blog({slug}:{slug?:string}){if(slug){const p=posts.find(x=>x.slug===slug)||posts[0];return <article className="article shell"><a href="/blog">← Back to the journal</a><p className="eyebrow">PET-FRIENDLY HOME · {p.date}</p><h1>{p.title}</h1><p className="lead">{p.excerpt}</p><img src={product.images[3]} alt="A pet-friendly living space"/><div className="article-copy"><p>Living with pets comes with its own kind of joy. A few small habits can keep your home feeling fresh without limiting their freedom.</p><h2>Start where everyone gathers</h2><p>Spend a few minutes on the sofa, bedding, and car seats. Sweep in one direction, gather the fur, and clean your tool. This tiny routine is more effective than a long cleanup at the end of the week.</p><blockquote>A pet-friendly home does not need to be perfect. It simply needs a rhythm that works.</blockquote><h2>Choose tools you can reuse</h2><p>A simple tool that is easy to see and store is far more likely to become part of your daily routine.</p></div></article>}return <section className="page shell"><div className="page-head"><p className="eyebrow">NOTES FROM FURLO</p><h1>The pet-friendly home journal</h1><p>Small ideas for a home that feels fresh, gentle, and refreshingly uncomplicated.</p></div><div className="post-grid">{posts.map((p,i)=><article key={p.slug}>{i===0&&<img src={product.images[3]} alt=""/>}<span>{p.date}</span><h2><a href={`/blog/${p.slug}`}>{p.title}</a></h2><p>{p.excerpt}</p><a href={`/blog/${p.slug}`}>Read story {icons.arrow}</a></article>)}</div></section>}
function NotFound(){return <section className="not-found"><span>404</span><h1>Looks like this page ran off after the cat.</h1><p>The address may have changed. Let us take you somewhere familiar.</p><a className="button" href="/">Back to home</a></section>}

function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter"><div><p className="eyebrow">LETTERS FROM FURLO</p><h2>Less fur on the sofa.<br/>More time together.</h2></div>{done?<p className="thanks">{icons.check} Thanks for joining us!</p>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><label className="sr-only">Email</label><input required type="email" placeholder="Your email address"/><button aria-label="Subscribe">{icons.arrow}</button><small>Get home-care tips and first access to offers. No clutter in your inbox.</small></form>}</section>}
function Footer({currency,setCurrency}:{currency:string;setCurrency:(s:string)=>void}){return <footer><div className="shell footer-grid"><div><a className="logo footer-logo" href="/">FUR<span>LO</span></a><p>Thoughtful little tools for easier, happier days with pets.</p><div className="social"><a href="#">Instagram</a><a href="#">Facebook</a></div></div><div><b>Discover</b><a href="/shop">Shop</a><a href="/about">Our Story</a><a href="/blog">Journal</a></div><div><b>Support</b><a href="/faq">Frequently Asked Questions</a><a href="/track-order">Track Your Order</a><a href="/contact">Contact</a><a href="/shipping">Shipping</a></div><div><b>Legal</b><a href="/returns">Returns</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="USD">United States · USD</option><option value="VND">Vietnam · VND</option></select></div></div><div className="footer-bottom shell"><span>© 2026 FURLO. Designed for better days with pets.</span><span>VISA · mastercard · JCB · Pay</span></div></footer>}

function Overlay({kind,close,cart,currency,add}:{kind:"cart"|"menu"|"search";close:()=>void;cart:ReturnType<typeof useCart>;currency:string;add:(v?:string)=>void}){const panel=useRef<HTMLDivElement>(null);const [q,setQ]=useState("");useEffect(()=>panel.current?.focus(),[]);const target=shippingTarget();return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={`drawer ${kind}`} ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label={kind==="cart"?"Cart":kind==="search"?"Search":"Menu"}><div className="drawer-head"><b>{kind==="cart"?`Cart (${cart.count})`:kind==="search"?"Search":"FURLO"}</b><button onClick={close} aria-label="Close">{icons.close}</button></div>{kind==="menu"?<nav className="mobile-nav"><a href="/shop">Shop <span>→</span></a><a href="/about">Our Story <span>→</span></a><a href="/blog">Journal <span>→</span></a><a href="/faq">FAQ <span>→</span></a><a href="/track-order">Track Your Order</a><a href="/contact">Contact</a></nav>:kind==="search"?<div className="drawer-search"><label>{icons.search}<input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="What are you looking for?"/></label>{(!q||product.title.toLowerCase().includes(q.toLowerCase())||"fur mitt sofa".includes(q.toLowerCase()))?<a className="mini-product" href={`/products/${product.slug}`}><img src={product.images[0]} alt=""/><span><small>SUGGESTED</small><b>{product.title}</b><em>{money(product.price,currency)}</em></span></a>:<div className="no-result">No results for “{q}”.</div>}<a className="text-link" href={`/search?q=${q}`}>View all results →</a></div>:cart.lines.length?<><div className="ship-note"><div><span style={{width:`${Math.min(100,cart.total/target*100)}%`}}/></div><p>{cart.total>=target?"You have unlocked free shipping!":`Add ${money(target-cart.total,currency)} more for free shipping.`}</p></div><CartLines cart={cart} currency={currency}/><div className="drawer-total"><div><span>Subtotal</span><strong>{money(cart.total,currency)}</strong></div><a className="button" href="/cart">View cart & checkout</a><small>Shipping is calculated at the next step.</small></div></>:<><EmptyCart/><div className="upsell"><p>A PET-PARENT FAVORITE</p><div className="mini-product"><img src={product.images[0]} alt=""/><span><b>{product.title}</b><em>{money(product.price,currency)}</em></span><button onClick={()=>add()}>＋</button></div></div></>}</div></div>}
function Cookie(){const [show,setShow]=useState(false);useEffect(()=>setShow(!localStorage.getItem("furlo-cookie-en")),[]);if(!show)return null;return <div className="cookie"><p>FURLO uses essential cookies to keep your cart working and improve your experience.</p><button onClick={()=>{localStorage.setItem("furlo-cookie-en","ok");setShow(false)}}>Accept</button></div>}
